apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openai-gpt3
  template:
    metadata:
      labels:
        app: openai-gpt3
    spec:
      containers:
        - name: react
          image: openai-gpt3
          imagePullPolicy: IfNotPresent
          ports:
           - containerPort: 3000
